### ISSUE TITLE
license file

### ISSUE THREAD

**Issue by idarlund** [svnpenn/sage#15]
Where is the license file?

**Comment by svnpenn** [comment]
What license would be good?

**Comment by idarlund** [comment]
For open source projects i would suggest MIT, GPL v3 or Apache v2

**Comment by svnpenn** [comment]
I dont really care about this, but if you can pick one I will probably commit it

**Comment by idarlund** [comment]
http://www.gnu.org/licenses/gpl-3.0.en.html

**Comment by svnpenn** [comment]
I will give one week for others to comment, otherwise I will put

GNU General Public License v3.0

**Comment by FunkyLoveCow** [comment]
The initial commit had the MIT License.
https://github.com/svnpenn/sage/blob/2f84a3f37db8a7cf830a456ec9443f93c009f5d1/LICENSE

I think it'd make sense to stick with that, unless there is a reason it was removed.

**Comment by svnpenn** [comment]
This has been fixed with 6a4a694303d7fc7497168b8b100215eeb5bebbde

**Comment by ArtOfCode-** [comment]
Just something to note: the license you pick can have a profound effect on your work, so you should probably be aware of what those effects are. They also have an effect on what contributions are allowed to do. If you've got queries, you may be able to ask at http://opensource.stackexchange.com/.

**Comment by svnpenn** [comment]
@ArtOfCode- yes, unfortunately I am now keenly aware. As I said before, I dont care about this stuff, but enough users have raised the issue so I felt the need to resolve it.

Not sure how much this can apply to a shell script, but in general, I do not want anything I write being used with proprietary or commercial software. GPL seems most in line with that.

**Comment by ArtOfCode-** [comment]
I think you're probably right there. Be aware that the GPL still doesn't restrict people making money from the software (it wouldn't be *technically* 'free' if it did), but it does require them to share the source code - which does mean that other people can clone and provide it for free.
